name: BukkitBridge
version: ${build.number}
description: BukkitBridge implements the Bukkit API to allow Bukkit plugins to be used on the Spout server.
author: SpoutDev
website: http://www.spout.org

main: org.spout.bukkit.BukkitBridge
platform: BOTH
